version: '3.8'
services:
  llm-watcher:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./config.yaml:/usr/share/llm-watcher/config.yaml:ro
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017
  mongo:
    image: mongo:6.0
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data: